---
title: "Analysis Draft"
output: html_document
date: "2022-11-22"
---

##Data Cleaning

```{r}
setwd("C:/Users/Peyto/Downloads")
MindfulnessDat <- read.csv("MindfulnessData_fullunmatched_raw_items_NadlerCarswellMinda.csv")
NadlerDat <- read.csv("MindfulnessDataExport_NadlerCarswellMinda2020.csv")
```

##Hypothesis 1 Analysis

```{r}
library(ggplot2)
library(tidyverse)

colnames(MindfulnessDat)[3] <- "group"

#at the moment, the section to the next hashtag is not working as intended
MindfulnessDat$grouping <- NA

for(i in 1:nrow(MindfulnessDat)){
  if(MindfulnessDat$group[i]=="Participant"){
    MindfulnessDat$grouping[i] <- 2
  }
  else{
    MindfulnessDat$grouping[i] <- 1
  }
}

data(MindfulnessDat) %>% filter(as.numeric(grouping)=="2")
#end

#because the filter did not work as I intended, I am going to try a t.test with 
#all participants to check if it will work in general

#well being score from responses to FFMQ baseline
colnames(NadlerDat)[24] <- "baseline_well_being"
NadlerDat[1, 24] <- NA
t.test(NadlerDat$baseline_well_being, mu = 3,alternative = "greater", na.rm = TRUE)
#error, but this is the draft so we are working through it
```

##Hypothesis 2 Analysis


##Hypothesis 3 Analysis

```{r}
library(ggplot2)
library(tidyverse)
library(car)

NadlerDat$baseline_well_being2 <- NA

for(i in 1:nrow(NadlerDat)){
  if(NadlerDat$baseline_well_being[i] < 3){
    NadlerDat$baseline_well_being2[i] <- "low"
  }else{
    NadlerDat$baseline_well_being2[i] <- "high"
  }
}
#error, but this is a step to figure out

#in essence the anova test would compare the high to the low groups, in the after
#section for a comparison between the control and participant groups
```
